#ifndef INCLUDED_CONFIG_H
#define INCLUDED_CONFIG_H

//#define NETWORK_ENABLE
#define CURRENT_SENSOR_ENABLE
#define VOLTAGE_SENSOR_ENABLE
#define RTC_ENABLE
#define MS_TIME_ENABLE

#endif /* INCLUDED_CONFIG_H */
